### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by BigglesDevs** [can-kat/cstealer#53]
when i get a error
```
Traceback (most recent call last):
  File "/home/kali/Downloads/cstealer/builder.pyw", line 9, in <module>
    app.iconbitmap("CStealer_assets\\img\\logo.ico")
  File "/usr/local/lib/python3.11/dist-packages/customtkinter/windows/ctk_tk.py", line 232, in iconbitmap
    super().wm_iconbitmap(bitmap, default)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2155, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bitmap "CStealer_assets\img\logo.ico" not defined
```

**Comment by can-kat** [comment]
Hello,

Please make sure you unzip all files correctly.

**Comment by BigglesDevs** [comment]
I have been but that's the error I get every time I extract them all properly
